# Generated by Django 2.0.4 on 2018-04-27 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dailystats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('story_id', models.CharField(max_length=30)),
                ('project', models.CharField(max_length=30)),
                ('Task', models.CharField(max_length=250)),
                ('Description', models.TextField(max_length=1000)),
                ('defects_filed', models.CharField(max_length=250)),
                ('defects_verified', models.CharField(max_length=250)),
                ('created_by', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='sprints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_sprint', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='dailystats',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailystatus.sprints'),
        ),
    ]
