# Generated by Django 2.0.4 on 2018-04-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailystatus', '0003_auto_20180427_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystats',
            name='defects_filed',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='dailystats',
            name='defects_verified',
            field=models.CharField(max_length=250),
        ),
    ]
